name: Model Training CICD

permissions:
  id-token: write
  contents: write

on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Train Model and Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train_model.py

          echo "## RF and LR Model Score" > report.md
          cat scores.txt >> report.md

          echo "## Confusion Matrix & Feature Importance" > report1.md
          echo '![](./ConfusionMatrix.png "Confusion Matrix")' >> report1.md
          echo '![](./FeatureImportance.png "Feature Importance")' >> report1.md

          cat report.md report1.md > combined_file.md

          cml comment create combined_file.md
